[package]
name = "editor"
version = "1.0.0"
authors = ["EncryptOS <encryptos@snaildos.com>"]
description = "A fast and efficient text editor for EncryptOS"
license-file = "LICENSE"
license = "GPL-3.0"
readme = "README.MD"
edition = "2022"

[dependencies]
gdk = "0.12.1"
tiny-keccak = "1.4.0"
pango = "0.8.0"
glib = "0.9.3"
faccess = "0.2.3"

[dependencies.sourceview]
features = ["v3_18"]
version = "0.8.0"

[dependencies.gtk]
features = ["v3_22"]
version = "0.8.1"

[dependencies.gio]
version = "0.8.1"
features = ["v2_44"]

[package.metadata.deb]
name = "com.encryptos.editor"
maintainer = "EncryptOS <encryptos@snaildos.com>"
copyright = "2022, EncryptOS <encryptos@snaildos.com>"
license-file = ["COPYING"]
depends = "$auto"
section = "utility"
priority = "optional"
maintainer-scripts = "make/pre_install.py make/post_install.py"
assets = [
    ["target/release/eddit", "/usr/bin/com.encryptos.editor", "755"],
    ["data/com.encryptos.editor.desktop", "/usr/share/applications/", "644"],
    ["data/com.encryptos.editor.gschema.xml", "/usr/share/glib-2.0/schemas/", "644"],
    ["res/com.encryptos.editor.svg", "/usr/share/icons/hicolor/scalable/apps/", "644"],
    ["res/icons/day.svg", "/opt/com.encryptos.editor/icons/", "644"],
    ["res/icons/night.svg", "/opt/com.encryptos.editor/icons/", "644"],
    ["data/styles/eddit-light.xml", "/usr/share/gtksourceview-3.0/styles/", "644"],
    ["data/styles/eddit-dark.xml", "/usr/share/gtksourceview-3.0/styles/", "644"],
]